on:
  workflow_dispatch:
  push:
    paths:
      - System/emulator/**

name: Build emulator

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Building macOS emulator
        run: make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AquariusPlusEmu_macOS
          path: System/emulator/build/AquariusPlusEmu_*.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Building Linux emulator
        run: make -C System/emulator
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: System/emulator/build/AquariusPlusEmu_*.zip
