on:
  workflow_dispatch:

name: Build Aquarius+ firmware
run-name: Build Aquarius+ firmware ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Get all Git tags
        run: git fetch --prune --unshallow --tags
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32s3
          path: "System/esp32"
      - name: Build release
        run: |
          cd System/esp32; ./do_release.sh nobuild
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Firmware_${{ github.ref_name }}
          path: System/esp32/firmware-*.zip
