on:
  workflow_dispatch:
  push:
    paths:
      - System/emulator/**

name: Build emulator

jobs:
  build-macos:
    name: Build macOS emulator
    runs-on: macos-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Building macOS emulator
        run: make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AquariusPlusEmu_macOS_${{ github.ref_name }}
          path: System/emulator/build/AquariusPlusEmu.app

  build-linux:
    name: Build Linux emulator
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
      - name: Building Linux emulator
        run: make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AquariusPlusEmu_Linux_Ubuntu_${{ github.ref_name }}
          path: System/emulator/build/aquarius_emu

  build-windows:
    name: Build Windows emulator
    runs-on: windows-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build app for release
        run: msbuild System\emulator\windows\aquarius-emu.vcxproj -t:rebuild -verbosity:normal -property:Configuration=Release -property:Platform=x64
      - name: Creating release directory structure
        run: |
          mkdir System\emulator\windows\x64\Release\AquariusPlusEmu
          copy System\emulator\windows\x64\Release\aquarius-emu.exe System\emulator\windows\x64\Release\AquariusPlusEmu\
          copy System\emulator\windows\SDL2-2.0.20\lib\x64\SDL2.dll System\emulator\windows\x64\Release\AquariusPlusEmu\
          copy System\emulator\aquarius.rom System\emulator\windows\x64\Release\AquariusPlusEmu\
          xcopy /E /I EndUser\sdcard System\emulator\windows\x64\Release\AquariusPlusEmu\sdcard
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AquariusPlusEmu_Windows_x64_${{ github.ref_name }}
          path: System/emulator/windows/x64/Release/AquariusPlusEmu
