on:
  workflow_dispatch:

name: Build Aquarius+ firmware
run-name: Build Aquarius+ firmware ${{ github.ref_name }} ${{ github.event.repository.pushed_at }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: ESP-IDF build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.1
          target: esp32s3
          path: "System/esp32"
