on:
  workflow_dispatch:
  push:
    paths:
      - System/emulator/**

name: Build macOS emulator

jobs:
  build-emu:
    runs-on: macos-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event, running on a ${{ runner.os }} server."
      - run: echo "Branch ${{ github.ref }}, repository ${{ github.repository }}."
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Building emulator
        run: make -C System/emulator
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: System/emulator/build/AquariusPlusEmu_*.zip
